### ISSUE TITLE
How to set player name?

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaSDK#12]
Hello.
Thank you for ConvivaSDK.
I need to set value for **Session Information** -> **Player & SDK Information** -> **Player name**. I tried `CIS_CCDK_METADATA_PLAYER_NAME`, but it does not work. Please tell me which key should I use?

**Comment by smadinen** [comment]
Hi @RomanPodymov 
Can you please check the tag name (CIS_SSDK_METADATA_PLAYER_NAME). Are you using the same?

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Yes, it is `CIS_SSDK_METADATA_PLAYER_NAME`, but it does not work. Should we use `CIS_SSDK_PLAYER_MODULE_NAME`?

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Found out that the problem was on my side, `CIS_SSDK_METADATA_PLAYER_NAME` works fine, sorry for disturbance.

**Comment by smadinen** [comment]
Thanks for the update @RomanPodymov
