### ISSUE TITLE
CDN Edge IP is always empty

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaSDK#2]
Hello.
Thank you for ConvivaSDK.
Found out that **CDN Edge IP** is always empty in our reports. I think it should be sent automatically. Found out that I can set `ConvivaContentInfo.cdnName` in code, but how can I set the value for **CDN Edge IP**? I also tried ConvivaAVFoundation v.4.0.7, but no success.

**Comment by smadinen** [comment]
Hi Roman,
 
If you are using only ConvivaSDK with out module, it's not auto collected.
To set manually, Below is sample usage to set CDN ip.
[videoAnalytics reportPlaybackMetric:CIS_SSDK_PLAYBACK_METRIC_CDN_IP value:@"1.2.3.4"];

In case of ConvivaAVFoundation Module Its auto collected with the version you mentioned (4.0.7).

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Thank you. Yes, we are using ConvivaAVFoundation 4.0.7, but **CDN Edge IP** is always empty. Probably we should always call `[videoAnalytics reportPlaybackMetric:CIS_SSDK_PLAYBACK_METRIC_CDN_IP value:@"1.2.3.4"];`.

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Found out that we must use ConvivaAVFoundation 3.1.12 for now. Could you please confirm that this version also collects **CDN Edge IP**?

**Comment by smadinen** [comment]
Hi Roman,

We don't auto collect CDN Edge IP in 3.1.12.
We started auto collecting CDN Edge IP starting from 4.0.0 version.

Thanks.

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Thanks for the clarification.
