### ISSUE TITLE
xcodebuild - ld: linking module flags 'Dwarf Version': IDs have conflicting behaviors

### ISSUE THREAD

**Issue by mackode** [Conviva/ConvivaSDK#3]
Hi,

Linker for simulator gives the following error:

ld: linking module flags 'Dwarf Version': IDs have conflicting behaviors in '/.../Pods/ConvivaSDK/Framework/iOS/ConvivaSDK.framework/ConvivaSDK(CISAdAnalyticsImpl.o)' and 'ld-temp.o' for architecture x86_64

Xcode - Version 12.0 (12A7209)
cocoapods - Version 1.9.3

When I build using Xcode UI it works fine, but when xcodebuild is used I get the error above.
I tried already to remove Derived Data.

Any help would be greatly appreciated.

**Comment by mackode** [comment]
I think the framework (4.0.7) is malformed:
```
$ dwarfdump Pods/ConvivaSDK/Framework/iOS/ConvivaSDK.framework/ConvivaSDK
error: Pods/ConvivaSDK/Framework/iOS/ConvivaSDK.framework/ConvivaSDK(armv7)(CISAdAnalyticsImpl.o): The file was not recognized as a valid object file
```

To compare:
```
$ dwarfdump Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds
Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds(x86_64): file format Mach-O 64-bit x86-64

.debug_info contents:
Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds(i386):   file format Mach-O 32-bit i386

.debug_info contents:
Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds(armv7):  file format Mach-O arm

.debug_info contents:
Pods/GoogleAds-IMA-iOS-SDK/GoogleInteractiveMediaAds.framework/GoogleInteractiveMediaAds(arm64):  file format Mach-O arm64

.debug_info contents:
```

**Comment by butchi-conviva** [comment]
Hi Makowski,

Thanks for sharing the inputs.

- If it is ok, can you please share the Xcode-build command with the args to look in to the issue.
- Have you enabled LTO(Link time Optimization) during compilation? If not, can you enable LLVM_LTO and share the results?
- Is it happening only with x86_64? Is armv7/arm64 compiling with out any issues?

Thanks,
Butchi

**Comment by mackode** [comment]
Hi Butchi,

- It is regular `xcodebuild` call, I did additional research and it looks it fails on our advanced security layer, which does extra compatibility checks. I can't give more details now, but please see my findings below.
- LTO is disabled, but I can see the same result when it is enabled.
- All available archs fails.

I did additional research and it looks the ConvivaSDK.framework was build on Xcode 11 against iOS SDK 13.0. During each build Xcode glues additional keys in `Info.plist` and when I inspect `ConvivaSDK.framework/Info.plist` I can see:

- DTXcode = 1100
- DTXcodeBuild = 11A420a
- DTSDKName = iphoneos13.0
- DTSDKBuild = 17A566

(https://xcodereleases.com/)

To compare this are values from `GoogleAds-IMA-iOS-SDK`:

- DTXcode = 1200
- DTXcodeBuild = 12A7209
- DTSDKName = iphoneos14.0
- DTSDKBuild = 18A390

It looks like they are incompatible on some metadata level, which is kind of visible in my second comment. 
Do you think it is possible that new ConvivaSDK.framework was built using old iOS SDK and Xcode?

Thanks

**Comment by mackode** [comment]
Hi Butchi, 

Here is the command that fails (I've changed the paths):

```text
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -target x86_64-apple-ios9.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.1.sdk -L/build/Release/xcode.derived/Build/Products/Release-iphonesimulator -F/build/Release/xcode.derived/Build/Products/Release-iphonesimulator -F/Pods/ConvivaSDK/Framework/iOS -F/Player -filelist /build/Release/xcode.derived/Build/Intermediates.noindex/build/Release-iphonesimulator/build/Objects-normal/x86_64/LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /../Release-iphonesimulator/build/Objects-normal/x86_64/HERE_lto.o -Xlinker -objc_abi_version -Xlinker 2 -Xlinker -final_output -Xlinker /Applications/HERE.app/TARGET -stdlib\=libc++ -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /build/Release/xcode.derived/Build/Intermediates.noindex/build/Release-iphonesimulator/build/Objects-normal/x86_64/TARGET.swiftmodule -ObjC -lz -framework AVFoundation -framework Accelerate -framework AdSupport -framework AudioToolbox -framework CFNetwork -framework ConvivaSDK -framework CoreBluetooth -framework CoreData -framework CoreFoundation -framework CoreGraphics -framework CoreMedia -framework CoreTelephony -framework CoreText -framework MediaAccessibility -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -weak_framework Network -weak_framework WebKit -ObjC -lxml2 -lz -weak_framework AVFoundation -framework Accelerate -framework AdSupport -framework AudioToolbox -framework CFNetwork -framework CoreBluetooth -framework CoreFoundation -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework CoreText -framework Foundation -framework GoogleInteractiveMediaAds -framework MediaAccessibility -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -weak_framework WebKit -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /build/Release/xcode.derived/Build/Intermediates.noindex/build/Release-iphonesimulator/TARGET.build/TARGET.app-Simulated.xcent -framework UserNotifications -framework JavaScriptCore -framework CoreMedia -framework CoreLocation -framework AdSupport-framework DebugPlugin -lsqlite3 -lPods-ios-TARGET -Xlinker -dependency_info -Xlinker /build/Release/xcode.derived/Build/Intermediates.noindex/build/Release-iphonesimulator/build/Objects-normal/x86_64/TARGET_dependency_info.dat -o /build/Release/xcode.derived/Build/Products/Release-iphonesimulator/TARGET.app/TARGET

ld: warning: linking module flags 'SDK Version': IDs have conflicting values ('[2 x i32] [i32 13, i32 0]' from /Pods/ConvivaSDK/Framework/iOS/ConvivaSDK.framework/ConvivaSDK(CISAdAnalyticsImpl.o) with '[2 x i32] [i32 14, i32 1]' from ld-temp.o)
ld: linking module flags 'Dwarf Version': IDs have conflicting behaviors in '/Pods/ConvivaSDK/Framework/iOS/ConvivaSDK.framework/ConvivaSDK(CISAdAnalyticsImpl.o)' and 'ld-temp.o' for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The only thing that I can see and is related to LTO:

`-object_path_lto path`

but it does not enable LTO. Is there something I missed?

Can you please let me know if this is intentional from your side that ConvivaSDK is build using Xcode 11 and iOS SDK 13?
Can you maybe build a version on Xcode 12 against iOS SDK 14 so I can test if it helps?

Best Regards,
Bartek

**Comment by butchi-conviva** [comment]
Hi Bartek,

Thanks for the details. Since Xcode 12 is out recently and many developers may still be using Xcode 11, To comply with Xcode 11, we built our SDK(4.0.7) with Xcode 11.

Could you please try with 4.0.6 which is built using Xcode 12. If your application serves the ads and IDFA is being used by the app, then 4.0.6 is the right version for you. 

Difference between 4.0.6 and 4.0.7 are below. Please see https://github.com/Conviva/ConvivaSDK/releases for more details.

4.0.6:

- Built with Xcode 12
- Collects IDFA(Need to build with Xcode 12 to comply with latest IDFA collection guidelines)

4.0.7

- Built with Xcode 11
- Does not collect IDFA

Please let us know if it helps.

Thanks,
Butchi

**Comment by mackode** [comment]
Hi Butchi,

It works fine with 4.0.6.

I think we are in 3rd group, we do not write an application and we do not serve ads directly (no IDFA):

4.0.8 :)
- Built with Xcode 12
- Does not collect IDFA

We cannot decide to use IDFA on behalf of our customers, it would be a huge change for us.
Is it possible for you to release an Xcode 12-based version of 4.0.7?

Thanks,
Bartek

**Comment by mackode** [comment]
Hi Butchi, we decided to go with 4.0.6. Thanks for your help.
