### ISSUE TITLE
Define a constant for "tags"

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaSDK#4]
Hello.
Thank you for ConvivaSDK.
As I can see at https://github.com/Conviva/ConvivaSDK/blob/master/DemoApp/iOS-ObjC/SampleApp/ViewController.m you have `CIS_SSDK_METADATA_ASSET_NAME`, `CIS_SSDK_METADATA_IS_LIVE` and other constants for the content info keys. But for "tags" you don't have it. Could you please define something like `CIS_SSDK_METADATA_TAGS`?

**Comment by smadinen** [comment]
Hi @RomanPodymov 

Thanks for the feedback.

Actually, we don't need to pass it as "tags" key. If we pass key-value pairs which are not pre defined, they will be treated as custom tags. For eg:., 

var contentInfo = [String: Any]()
contentInfo["my_custom_tag_key"] = "my_custom_tag_value"
videoAnalytics.setContentInfo(contentInfo)

So specifically we don't need to define constant for tags anymore.

Information on how to pass custom tags is updated in Community. 
Looks like it is not updated in the sample app which you shared above. We will update it sooner.

Thanks.

**Comment by smadinen** [comment]
Closing based on above comments.

Please reopen in case if required. Thanks
