### ISSUE TITLE
Don't see any data at https://touchstone.conviva.com/sources when CIS_SSDK_SETTINGS_GATEWAY_URL is not set

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaSDK#7]
Hello.
When we started to develop our app we set `CIS_SSDK_SETTINGS_GATEWAY_URL` as you did it in https://github.com/Conviva/ConvivaSDK/blob/master/DemoApp/iOS-Swift/SDKSwiftApp/ViewController.swift. But _the default value is highly recommended in production environments_ and we don't see any data at https://touchstone.conviva.com/sources when `CIS_SSDK_SETTINGS_GATEWAY_URL` is not set. Is it a known issue?

**Comment by smadinen** [comment]
Hi @RomanPodymov 

Touchstone is the tool which is used for testing at the time of integration.
Can you please check if you can see the data on Pulse in the case of Production environment.

Thanks.

**Comment by RomanPodymov** [comment]
Hello @smadinen 
Yes, at https://pulse.conviva.com we can see all data, thanks for the clarification.
